### ISSUE TITLE
 NEED A INNOCENT-FRANCIOS - CRITICAL - BLOCKING - URGENT

### ISSUE THREAD

**Issue by FrLallemandArhs** [corem/NationalMuseumOfPossumDecorativeArtsHistory#10]
As with calimero-francios issue, we need a new innocent-francios icon, also TOP PRIORITY !

Management asked for it !

It is required before the release, 3 weeks ago !

**Comment by corem** [comment]
A Francios is never innocent. Please, let's focus on realistic tasks.
